name: LaptimerCore CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      run: cmake --preset debug .
    - name: make
      run: cmake --build --preset debug
    - name: test
      run: ctest -V