name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt update && sudo apt install libsdl2-dev
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: cmake --preset github-ci-debug
      - name: make
        run: cmake --build --preset github-ci-debug
      - name: test
        run: ctest --preset github-test -V --output-junit test_results.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "build/github-ci-debug/test_results.xml"
