# SPDX-FileCopyrightText: 2021 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Blabby CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.*'
        cache: 'true'
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install doxygen libsdl2-dev
    - name: checkout
      uses: actions/checkout@v4
    - name: build and test
      run: |
        cmake --preset github-ci-debug
        cmake --build --preset github-ci-debug -- -j
        ctest --preset github-ci-test --output-on-failure
      env:
        QT_QPA_PLATFORM: offscreen
