name: Clang-Tidy Review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run clang-tidy
      id: review
      uses: ZedThree/clang-tidy-review@v0.10.1
      with:
        build_dir: build/github-ci-debug
        config_file: .clang-tidy
        apt_packages: libsdl2-dev,qtbase5-dev,qtdeclarative5-dev,qtlocation5-dev,qtpositioning5-dev,libsqlite3-dev
        cmake_command: cmake --preset github-ci-debug
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
