name: LappyCore Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt update && sudo apt install libsdl2-dev clang-tidy-14
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: configure
        run: cmake --preset github-ci-debug
      - name: make
        run: cmake --build --preset github-ci-debug -- -j12
      - name: test
        run: ctest --preset github-test -V --output-junit test_results.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "build/github-ci-debug/test_results.xml"
      - name: Create results directory
        run: |
          mkdir clang-tidy-result
      - name: Analyze
        run: |
          pip3 install pyyaml
          git diff -U0 HEAD^ | /usr/bin/clang-tidy-diff-14.py -p1 -path build/github-ci-debug -export-fixes clang-tidy-result/fixes.yml
      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: clang-tidy-result/fixes.yml
          request_changes: false
          suggestions_per_comment: 10 
