name: LappyCore Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt update && sudo apt install libsdl2-dev clang-tidy-14
      - name: install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: cmake --preset github-ci-debug
      - name: make
        run: cmake --build --preset github-ci-debug -- -j12
      - name: test
        run: ctest --preset github-test -V --output-junit test_results.xml
      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "build/github-ci-debug/test_results.xml"
      - name: clang-tidy-analyze
        run: |
          pip3 install pyyaml
          git diff origin/main | /usr/bin/clang-tidy-diff-14.py -p1 -path build/github-ci-debug -export-fixes fixes.yml
      - name: post clang-tidy pull request comments
        id: comments
        uses: platisd/clang-tidy-pr-comments@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: fixes.yml
          suggestion- name: publish clang-tidy results
      - name: check clang-tidy results
        run: |
          if [ -e fixes.yml ]; then
            filesize=$(stat -c '%s' fixes.yml)
            if [ $filesize -gt 0 ]; then
              echo "clang-tidy warnings found."
              exit 1
            else
              exit 0
            fi
          fi
