# SPDX-FileCopyrightText: 2024 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Generate VCPKG Cache

on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Update_VCPKG_Cache:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
